version: "3.9"

# https://hub.docker.com/_/redis
services:
  # https://hub.docker.com/_/redis
    redis:
        container_name: redis
        image: redis:6-alpine
        command: redis-server --requirepass <REDIS_PASSWORD>
        restart: unless-stopped
      # ports:
      #     - "6379:6379"
        networks:
            redis:
                ipv4_address: 10.20.96.2
        dns:
            - 8.8.8.8
            - 8.8.4.4
            - 2001:4860:4860::8888
            - 2001:4860:4860::8844

  # https://hub.docker.com/_/redis
    redis-nopw:
        container_name: redis-nopw
        image: redis:6-alpine
        restart: unless-stopped
      # ports:
      #     - "6379:6379"
        networks:
            redis-nopw:
                ipv4_address: 10.20.112.2
        dns:
            - 8.8.8.8
            - 8.8.4.4
            - 2001:4860:4860::8888
            - 2001:4860:4860::8844

networks:
    redis:
        name: redis
        ipam:
            driver: default
            config:
                - subnet: "10.20.96.0/20"
                  gateway: 10.20.96.1
    redis-nopw:
        name: redis-nopw
        ipam:
            driver: default
            config:
                - subnet: "10.20.112.0/20"
                  gateway: 10.20.112.1
