version: "3.9"

services:
  # https://hub.docker.com/r/containrrr/watchtower
    watchtower:
        container_name: watchtower
        image: containrrr/watchtower:latest
        command: --cleanup --rolling-restart --schedule "0 0 4 * * *"
        restart: always
        networks:
            watchtower:
                ipv4_address: 10.24.3.2
        dns:
            - 8.8.8.8
            - 8.8.4.4
            - 2001:4860:4860::8888
            - 2001:4860:4860::8844
        environment:
            TZ: 'Europe/Berlin'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

networks:
    watchtower:
        name: watchtower
        ipam:
            driver: default
            config:
                - subnet: "10.24.3.0/24"
                  gateway: 10.24.3.1
