version: "3.9"

# https://hub.docker.com/r/writl/pyload
services:
  # https://hub.docker.com/r/writl/pyload
    pyload:
        container_name: pyload
        image: writl/pyload:latest
        restart: unless-stopped
        ports:
            - "8000:8000"
        networks:
            pyload:
                ipv4_address: 10.24.7.2
        dns:
            - 8.8.8.8
            - 8.8.4.4
            - 2001:4860:4860::8888
            - 2001:4860:4860::8844
        environment:
            TZ: Europe/Berlin
            UID: "1024"
            GID: "100"
        volumes:
            - /volume1/docker/pyload:/opt/pyload/pyload-config
            - /volume1/downloads:/opt/pyload/Downloads

networks:
    pyload:
        name: pyload
        ipam:
            driver: default
            config:
                - subnet: "10.24.7.0/24"
                  gateway: 10.24.7.1
