version: "3.9"

services:
  # https://hub.docker.com/_/nextcloud
    nextcloud:
        container_name: nextcloud
        image: nextcloud:22-apache
        restart: unless-stopped
        networks:
            nextcloud:
                ipv4_address: 10.20.160.2
            mariadb:
                ipv4_address: 10.20.0.210
            redis:
                ipv4_address: 10.20.96.210
        ports:
            - "2210:80"
          # - "4210:443"
        dns:
            - 8.8.8.8
            - 8.8.4.4
            - 2001:4860:4860::8888
            - 2001:4860:4860::8844
        volumes:
            - /volume1/docker/nextcloud/nextcloud:/var/www/html
            - /volume1/docker/nextcloud/data:/var/www/html/data
            - /volume1/docker/nextcloud/php-filesize.ini:/usr/local/etc/php/conf.d/php-filesize.ini
            - /volume1/docker/nextcloud/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf
        environment:
          # MYSQL
            MYSQL_DATABASE: "nextcloud"
            MYSQL_USER: "nextcloud"
            MYSQL_PASSWORD: '<MYSQL_NEXTCLOUD_PASSWORD>'
            MYSQL_HOST: "mariadb"
          # REDIS
            REDIS_HOST: "redis"
            REDIS_HOST_PORT: "6379"
            REDIS_HOST_PASSWORD: '<REDIS_HOST_PASSWORD>'
          # REVERSE_PROXY
          # only if your nextcloud-container is behind a reverse proxy
            APACHE_DISABLE_REWRITE_IP: "1"
            TRUSTED_PROXIES: "nginx"
            OVERWRITEHOST: "nextcloud.3x3cut0r.synology.me"
            OVERWRITEPROTOCOL: "https"
          # OVERWRITEWEBROOT: '/domain.tld/nextcloud'
          # OVERWRITECONDADDR: '^10\.0\.0\.1$'

  # https://hub.docker.com/r/onlyoffice/documentserver
    onlyoffice-documentserver:
        container_name: onlyoffice-documentserver
        image: onlyoffice/documentserver:latest
        restart: unless-stopped
        networks:
            nextcloud:
                ipv4_address: 10.20.160.3
      # ports:
      #     - 80:80
      #     - 443:443
        dns:
            - 8.8.8.8
            - 8.8.4.4
            - 2001:4860:4860::8888
            - 2001:4860:4860::8844
      # environment:
      #     ONLYOFFICE_HTTPS_HSTS_ENABLED: "true"
      #     ONLYOFFICE_HTTPS_HSTS_MAXAGE: "31536000"
      #     SSL_CERTIFICATE_PATH: "/var/www/onlyoffice/Data/certs/onlyoffice.crt"
      #     SSL_KEY_PATH: "/var/www/onlyoffice/Data/certs/onlyoffice.key"
      #     SSL_DHPARAM_PATH: "/var/www/onlyoffice/Data/certs/dhparam.pem"
      #     SSL_VERIFY_CLIENT: "false"
        volumes:
            - /volume1/docker/nextcloud-onlyoffice-documentserver/Data:/var/www/onlyoffice/Data
            - /volume1/docker/nextcloud-onlyoffice-documentserver/log:/var/log/onlyoffice

networks:
    nextcloud:
        name: nextcloud
        ipam:
            driver: default
            config:
                - subnet: "10.20.160.0/20"
                  gateway: 10.20.160.1
    mariadb:
        external:
            name: mariadb
    redis:
        external:
            name: redis
