version: "3.9"

services:
  # https://hub.docker.com/r/portainer/portainer-ce
    portainer:
        container_name: portainer
        image: portainer/portainer-ce:alpine
        restart: always
        env_file: ../../env-files/portainer.env
        networks:
            portainer:
                ipv4_address: 10.24.1.2
        ports:
          # - 8000:8000
            - 2101:9000
        environment:
            COMPOSE_HTTP_TIMEOUT: 240
        dns:
            - 8.8.8.8
            - 8.8.4.4
            - 2001:4860:4860::8888
            - 2001:4860:4860::8844
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /volume1/docker/portainer:/data

networks:
    portainer:
        name: portainer
        ipam:
            driver: default
            config:
                - subnet: "10.24.1.0/24"
                  gateway: 10.24.1.1
