version: "3.9"

# https://hub.docker.com/r/jonaswinkler/paperless-ng
services:
  # https://hub.docker.com/r/thecodingmachine/gotenberg
    gotenberg:
        container_name: gotenberg
        image: thecodingmachine/gotenberg:latest
        restart: unless-stopped
      # ports:
      #     - "3000:3000"
        networks:
            paperless-ng:
                ipv4_address: 10.24.21.3
        dns:
            - 8.8.8.8
            - 8.8.4.4
            - 2001:4860:4860::8888
            - 2001:4860:4860::8844
        environment:
            DISABLE_GOOGLE_CHROME: 1

  # https://hub.docker.com/r/apache/tika
    tika:
        container_name: tika
        image: apache/tika:latest
        restart: unless-stopped
      # ports:
      #     - "9998:9998"
        networks:
            paperless-ng:
                ipv4_address: 10.24.21.4
        dns:
            - 8.8.8.8
            - 8.8.4.4
            - 2001:4860:4860::8888
            - 2001:4860:4860::8844

  # https://hub.docker.com/r/jonaswinkler/paperless-ng
    paperless-ng:
        container_name: paperless-ng
        image: jonaswinkler/paperless-ng:latest
        restart: unless-stopped
        ports:
            - "2121:8000"
        networks:
            paperless-ng:
                ipv4_address: 10.24.21.2
            postgres:
                ipv4_address: 10.20.16.121
            redis-nopw:
                ipv4_address: 10.20.112.121
        dns:
            - 8.8.8.8
            - 8.8.4.4
            - 2001:4860:4860::8888
            - 2001:4860:4860::8844
        environment:
            PAPERLESS_TIME_ZONE: "Europe/Berlin"
            USERMAP_UID: "1024"
            USERMAP_GID: "100"
            PAPERLESS_REDIS: "redis://redis-nopw:6379"
            PAPERLESS_DBHOST: "postgres"
            PAPERLESS_DBPORT: "5432"
            PAPERLESS_DBNAME: "paperless-ng"
            PAPERLESS_DBUSER: "paperless-ng"
            PAPERLESS_DBPASS: '<PAPERLESS_DBPASS>'
            PAPERLESS_DBSSLMODE: "prefer"
            PAPERLESS_LOGROTATE_MAX_SIZE: "1"
            PAPERLESS_LOGROTATE_MAX_BACKUPS: "20"
            PAPERLESS_SECRET_KEY: '<PAPERLESS_SECRET_KEY>'
            PAPERLESS_OCR_LANGUAGE: "deu"
            PAPERLESS_ADMIN_USER: "admin"
            PAPERLESS_ADMIN_PASSWORD: '<PAPERLESS_ADMIN_PASSWORD>'
            PAPERLESS_ADMIN_MAIL: "executor55@gmx.de"
            PAPERLESS_OCR_MODE: "skip"
            PAPERLESS_OCR_CLEAN: "clean"
            PAPERLESS_OCR_DESKEW: "true"
            PAPERLESS_OCR_ROTATE_PAGES: "true"
            PAPERLESS_OCR_ROTATE_PAGES_THRESHOLD: "12"
            PAPERLESS_OCR_OUTPUT_TYPE: "pdfa"
            PAPERLESS_OCR_PAGES: "0"
            PAPERLESS_OCR_IMAGE_DPI: ""
            PAPERLESS_TIKA_ENABLED: "1"
            PAPERLESS_TIKA_GOTENBERG_ENDPOINT: "http://gotenberg:3000"
            PAPERLESS_TIKA_ENDPOINT: "http://tika:9998"
            PAPERLESS_TASK_WORKERS: "2"
            PAPERLESS_THREADS_PER_WORKER: "1"
            PAPERLESS_WEBSERVER_WORKERS: "2"
            PAPERLESS_CONSUMER_POLLING: "0"
            PAPERLESS_CONSUMER_DELETE_DUPLICATES: "false"
            PAPERLESS_CONSUMER_RECURSIVE: "false"
            PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "false"
            PAPERLESS_CONVERT_MEMORY_LIMIT: "0"
            PAPERLESS_CONVERT_TMPDIR: ""
            PAPERLESS_OPTIMIZE_THUMBNAILS: "true"
            PAPERLESS_POST_CONSUME_SCRIPT: ""
            PAPERLESS_FILENAME_DATE_ORDER: ""
            PAPERLESS_THUMBNAIL_FONT_NAME: "/usr/share/fonts/liberation/LiberationSerif-Regular.ttf"
            PAPERLESS_IGNORE_DATES: "<PAPERLESS_IGNORE_DATES>" # e.g.: "1900-01-31,31.01.1900" (date of birth)
            PAPERLESS_DATE_ORDER: "DMY"
            PAPERLESS_CONVERT_BINARY: "/usr/bin/convert"
            PAPERLESS_GS_BINARY: "/usr/bin/gs"
            PAPERLESS_OPTIPNG_BINARY: "/usr/bin/optipng"
        volumes:
            - /volume1/docker/paperless-ng/data:/usr/src/paperless/data
            - /volume1/docker/paperless-ng/media:/usr/src/paperless/media
            - /volume1/docker/paperless-ng/export:/usr/src/paperless/export
            - /volume1/docker/paperless-ng/consume:/usr/src/paperless/consume
        depends_on:
            - gotenberg
            - tika

networks:
    paperless-ng:
        name: paperless-ng
        ipam:
            driver: default
            config:
                - subnet: "10.24.21.0/24"
                  gateway: 10.24.21.1
    postgres:
        external:
            name: postgres
    redis-nopw:
        external:
            name: redis-nopw
